/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProducaoRouteImport } from './routes/producao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CaixaRouteImport } from './routes/caixa'
import { Route as CardapioRouteImport } from './routes/cardapio'
import { Route as ChamadaRouteImport } from './routes/chamada'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const ProducaoRoute = ProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaRoute = CaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const CardapioRoute = CardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadaRoute = ChamadaRouteImport.update({
  id: '/chamada',
  path: '/chamada',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/caixa': typeof CaixaRoute
  '/cardapio': typeof CardapioRoute
  '/chamada': typeof ChamadaRoute
  '/login': typeof LoginRoute
  '/producao': typeof ProducaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/caixa': typeof CaixaRoute
  '/cardapio': typeof CardapioRoute
  '/chamada': typeof ChamadaRoute
  '/login': typeof LoginRoute
  '/producao': typeof ProducaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/caixa': typeof CaixaRoute
  '/cardapio': typeof CardapioRoute
  '/chamada': typeof ChamadaRoute
  '/login': typeof LoginRoute
  '/producao': typeof ProducaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/caixa' | '/cardapio' | '/chamada' | '/login' | '/producao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/caixa' | '/cardapio' | '/chamada' | '/login' | '/producao'
  id: '__root__' | '/' | '/admin' | '/caixa' | '/cardapio' | '/chamada' | '/login' | '/producao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CaixaRoute: typeof CaixaRoute
  CardapioRoute: typeof CardapioRoute
  ChamadaRoute: typeof ChamadaRoute
  LoginRoute: typeof LoginRoute
  ProducaoRoute: typeof ProducaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/producao': {
      id: '/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof ProducaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa': {
      id: '/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof CaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardapio': {
      id: '/cardapio'
      path: '/cardapio'
      fullPath: '/cardapio'
      preLoaderRoute: typeof CardapioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamada': {
      id: '/chamada'
      path: '/chamada'
      fullPath: '/chamada'
      preLoaderRoute: typeof ChamadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CaixaRoute: CaixaRoute,
  CardapioRoute: CardapioRoute,
  ChamadaRoute: ChamadaRoute,
  LoginRoute: LoginRoute,
  ProducaoRoute: ProducaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
